// UI strings in the eight Wron languages. English is the reference: every
// other table must have exactly the same keys (test/strings.test.js).
// {name} placeholders are filled by t(key, {name: value}).
//
// When the Wron Main Panel's own i18n system is integrated, these tables are
// meant to move into it; the keys stay the same.

export const LOCALES = ['en', 'tr', 'es', 'pt', 'fr', 'de', 'ru', 'zh-Hans'];

const en = {
  'title': 'Motion Path',
  'dev.banner': 'Developer harness — mock host, not connected to VEGAS',
  'tool.select': 'Select / move',
  'tool.add': 'Add point',
  'tool.delete': 'Delete point',
  'undo': 'Undo',
  'redo': 'Redo',
  'mode.corner': 'Corner',
  'mode.smooth': 'Smooth',
  'mode.free': 'Independent handles',
  'path.close': 'Closed path',
  'path.reverse': 'Reverse path direction',
  'view.grid': 'Grid',
  'view.snap': 'Snap',
  'view.fitPath': 'Fit path',
  'view.fitFrame': 'Fit frame',
  'view.zoomIn': 'Zoom in',
  'view.zoomOut': 'Zoom out',
  'view.inspector': 'Settings',
  'sec.path': 'Path',
  'sec.preview': 'Preview',
  'sec.timing': 'Timing',
  'sec.transform': 'Transform',
  'sec.orientation': 'Orientation',
  'sec.blur': 'Motion blur',
  'sec.presets': 'Presets',
  'path.summary': '{n} points · {kind} · length {len}',
  'path.kindOpen': 'open',
  'path.kindClosed': 'closed',
  'path.empty': 'Empty path — use Add point to place points.',
  'path.invalid': 'The stored path data cannot be read ({msg}). It was left unchanged; editing is disabled.',
  'path.future': 'The stored path data was saved by a newer version. It was left unchanged; editing is disabled.',
  'sel.none': 'No point selected',
  'sel.many': '{n} points selected',
  'point.x': 'X',
  'point.y': 'Y',
  'point.mode': 'Point type',
  'point.in': 'Handle in',
  'point.out': 'Handle out',
  'point.delete': 'Delete selected',
  'units.norm': 'Normalized',
  'units.px': 'Pixels',
  'preview.progress': 'Preview position',
  'preview.note': 'Preview only — animate Progress on the timeline.',
  'p.startOffset': 'Start offset',
  'p.reverseTravel': 'Reverse travel',
  'p.endBehavior': 'Open path ends',
  'p.speedMode': 'Speed',
  'p.easing': 'Easing',
  'p.easeP1': 'Custom ease P1',
  'p.easeP2': 'Custom ease P2',
  'p.pivot': 'Source pivot',
  'p.offset': 'Position offset',
  'p.uniformScale': 'Uniform scale',
  'p.scale': 'Scale (%)',
  'p.rotation': 'Rotation (°)',
  'p.opacity': 'Opacity (%)',
  'p.orient': 'Orient to path',
  'p.orientOffset': 'Rotation offset (°)',
  'p.orientMode': 'Face',
  'p.orientSmooth': 'Direction smoothing (%)',
  'p.blur': 'Motion blur',
  'p.shutterAngle': 'Shutter angle (°)',
  'p.shutterPhase': 'Shutter phase (°)',
  'p.blurAdaptive': 'Adaptive samples',
  'p.blurSamples': 'Samples',
  'p.blurMaxSamples': 'Max samples',
  'p.blurPreview': 'Preview blur',
  'o.clamp': 'Clamp',
  'o.extend': 'Extend',
  'o.loop': 'Loop',
  'o.pingPong': 'Ping-pong',
  'o.constantSpeed': 'Constant speed',
  'o.equalTime': 'Equal time per segment',
  'o.linear': 'Linear',
  'o.easeIn': 'Ease in',
  'o.easeOut': 'Ease out',
  'o.easeInOut': 'Ease in-out',
  'o.backOut': 'Back out (overshoot)',
  'o.custom': 'Custom',
  'o.travel': 'Travel direction',
  'o.pathDir': 'Path direction',
  'o.full': 'Full',
  'o.reduced': 'Reduced',
  'o.off': 'Off',
  'params.unavailable': 'Effect parameters are not available from this host.',
  'presets.builtin': 'Built-in paths',
  'preset.straight': 'Straight',
  'preset.arc': 'Arc',
  'preset.circle': 'Circle',
  'preset.ellipse': 'Ellipse',
  'preset.s-curve': 'S-curve',
  'preset.zigzag': 'Zigzag',
  'preset.spiral': 'Spiral',
  'presets.user': 'Saved presets',
  'presets.name': 'Preset name',
  'presets.level': 'Contents',
  'level.geometry': 'Path only',
  'level.look': 'Path + look',
  'level.timing': 'Path + look + timing',
  'presets.timingMode': 'Timing',
  'timing.fit': 'Fit to event',
  'timing.preserve': 'Preserve timing',
  'presets.save': 'Save',
  'presets.load': 'Load',
  'presets.delete': 'Delete',
  'presets.none': 'No saved presets yet.',
  'presets.unavailable': 'Saving presets needs storage from the Wron panel; this host does not provide it.',
  'presets.timingUnavailable': 'Timing needs keyframe access and the event duration from the host.',
  'presets.saved': 'Preset “{name}” saved.',
  'presets.loaded': 'Preset “{name}” loaded.',
  'presets.skipped': 'Not applied because they are animated: {list}',
  'presets.nameRequired': 'Enter a preset name.',
  'msg.writeFailed': 'Could not write to the project: {msg}',
  'hint.select': 'Drag points or handles · Shift: add to selection · Alt: independent handle · double-click curve: add point',
  'hint.add': 'Click the curve to split it, elsewhere to append · drag to pull handles',
  'hint.delete': 'Click a point to delete it',
  'hint.readonly': 'Read-only',
  'params.animated': 'Animated — edit on the timeline',
  'view.units': 'Units',
};

const tr = {
  'title': 'Hareket Yolu',
  'dev.banner': 'Geliştirici ortamı — sahte host, VEGAS’a bağlı değil',
  'tool.select': 'Seç / taşı',
  'tool.add': 'Nokta ekle',
  'tool.delete': 'Nokta sil',
  'undo': 'Geri al',
  'redo': 'Yinele',
  'mode.corner': 'Köşe',
  'mode.smooth': 'Yumuşak',
  'mode.free': 'Bağımsız kollar',
  'path.close': 'Kapalı yol',
  'path.reverse': 'Yol yönünü ters çevir',
  'view.grid': 'Izgara',
  'view.snap': 'Yapıştır',
  'view.fitPath': 'Yola sığdır',
  'view.fitFrame': 'Kareye sığdır',
  'view.zoomIn': 'Yakınlaştır',
  'view.zoomOut': 'Uzaklaştır',
  'view.inspector': 'Ayarlar',
  'sec.path': 'Yol',
  'sec.preview': 'Önizleme',
  'sec.timing': 'Zamanlama',
  'sec.transform': 'Dönüşüm',
  'sec.orientation': 'Yönlenme',
  'sec.blur': 'Hareket bulanıklığı',
  'sec.presets': 'Hazır ayarlar',
  'path.summary': '{n} nokta · {kind} · uzunluk {len}',
  'path.kindOpen': 'açık',
  'path.kindClosed': 'kapalı',
  'path.empty': 'Yol boş — nokta yerleştirmek için Nokta ekle aracını kullanın.',
  'path.invalid': 'Kayıtlı yol verisi okunamıyor ({msg}). Veri değiştirilmedi; düzenleme kapalı.',
  'path.future': 'Kayıtlı yol verisi daha yeni bir sürümle kaydedilmiş. Veri değiştirilmedi; düzenleme kapalı.',
  'sel.none': 'Seçili nokta yok',
  'sel.many': '{n} nokta seçili',
  'point.x': 'X',
  'point.y': 'Y',
  'point.mode': 'Nokta tipi',
  'point.in': 'Giriş kolu',
  'point.out': 'Çıkış kolu',
  'point.delete': 'Seçileni sil',
  'units.norm': 'Normalize',
  'units.px': 'Piksel',
  'preview.progress': 'Önizleme konumu',
  'preview.note': 'Yalnızca önizleme — Progress’i zaman çizelgesinde canlandırın.',
  'p.startOffset': 'Başlangıç kayması',
  'p.reverseTravel': 'Ters yönde ilerle',
  'p.endBehavior': 'Açık yol uçları',
  'p.speedMode': 'Hız',
  'p.easing': 'Yumuşatma',
  'p.easeP1': 'Özel eğri P1',
  'p.easeP2': 'Özel eğri P2',
  'p.pivot': 'Kaynak pivotu',
  'p.offset': 'Konum ofseti',
  'p.uniformScale': 'Orantılı ölçek',
  'p.scale': 'Ölçek (%)',
  'p.rotation': 'Döndürme (°)',
  'p.opacity': 'Opaklık (%)',
  'p.orient': 'Yola göre yönlen',
  'p.orientOffset': 'Döndürme ofseti (°)',
  'p.orientMode': 'Bakış yönü',
  'p.orientSmooth': 'Yön yumuşatma (%)',
  'p.blur': 'Hareket bulanıklığı',
  'p.shutterAngle': 'Obtüratör açısı (°)',
  'p.shutterPhase': 'Obtüratör fazı (°)',
  'p.blurAdaptive': 'Uyarlanabilir örnekleme',
  'p.blurSamples': 'Örnek sayısı',
  'p.blurMaxSamples': 'En fazla örnek',
  'p.blurPreview': 'Önizleme bulanıklığı',
  'o.clamp': 'Sınırla',
  'o.extend': 'Uzat',
  'o.loop': 'Döngü',
  'o.pingPong': 'Git-gel',
  'o.constantSpeed': 'Sabit hız',
  'o.equalTime': 'Segment başına eşit süre',
  'o.linear': 'Doğrusal',
  'o.easeIn': 'Yavaş başla',
  'o.easeOut': 'Yavaş bitir',
  'o.easeInOut': 'Yavaş başla ve bitir',
  'o.backOut': 'Geri sekme (aşma)',
  'o.custom': 'Özel',
  'o.travel': 'Hareket yönü',
  'o.pathDir': 'Yol yönü',
  'o.full': 'Tam',
  'o.reduced': 'Azaltılmış',
  'o.off': 'Kapalı',
  'params.unavailable': 'Efekt parametreleri bu host’tan alınamıyor.',
  'presets.builtin': 'Hazır yollar',
  'preset.straight': 'Düz',
  'preset.arc': 'Yay',
  'preset.circle': 'Daire',
  'preset.ellipse': 'Elips',
  'preset.s-curve': 'S eğrisi',
  'preset.zigzag': 'Zikzak',
  'preset.spiral': 'Spiral',
  'presets.user': 'Kayıtlı ayarlar',
  'presets.name': 'Ayar adı',
  'presets.level': 'İçerik',
  'level.geometry': 'Yalnızca yol',
  'level.look': 'Yol + görünüm',
  'level.timing': 'Yol + görünüm + zamanlama',
  'presets.timingMode': 'Zamanlama',
  'timing.fit': 'Event süresine uydur',
  'timing.preserve': 'Özgün zamanlamayı koru',
  'presets.save': 'Kaydet',
  'presets.load': 'Yükle',
  'presets.delete': 'Sil',
  'presets.none': 'Henüz kayıtlı ayar yok.',
  'presets.unavailable': 'Ayar kaydetmek için Wron panelinin depolaması gerekir; bu host bunu sağlamıyor.',
  'presets.timingUnavailable': 'Zamanlama için host’tan keyframe erişimi ve event süresi gerekir.',
  'presets.saved': '“{name}” kaydedildi.',
  'presets.loaded': '“{name}” yüklendi.',
  'presets.skipped': 'Animasyonlu oldukları için uygulanmadı: {list}',
  'presets.nameRequired': 'Bir ayar adı girin.',
  'msg.writeFailed': 'Projeye yazılamadı: {msg}',
  'hint.select': 'Noktaları veya kolları sürükleyin · Shift: seçime ekle · Alt: bağımsız kol · eğriye çift tık: nokta ekle',
  'hint.add': 'Bölmek için eğriye, sona eklemek için boşluğa tıklayın · kolları çekmek için sürükleyin',
  'hint.delete': 'Silmek için bir noktaya tıklayın',
  'hint.readonly': 'Salt okunur',
  'params.animated': 'Animasyonlu — zaman çizelgesinde düzenleyin',
  'view.units': 'Birim',
};

const es = {
  'title': 'Trayectoria de movimiento',
  'dev.banner': 'Entorno de desarrollo — host simulado, no conectado a VEGAS',
  'tool.select': 'Seleccionar / mover',
  'tool.add': 'Añadir punto',
  'tool.delete': 'Eliminar punto',
  'undo': 'Deshacer',
  'redo': 'Rehacer',
  'mode.corner': 'Esquina',
  'mode.smooth': 'Suave',
  'mode.free': 'Manejadores independientes',
  'path.close': 'Trayectoria cerrada',
  'path.reverse': 'Invertir dirección',
  'view.grid': 'Cuadrícula',
  'view.snap': 'Ajustar',
  'view.fitPath': 'Encuadrar trayectoria',
  'view.fitFrame': 'Encuadrar fotograma',
  'view.zoomIn': 'Acercar',
  'view.zoomOut': 'Alejar',
  'view.inspector': 'Ajustes',
  'sec.path': 'Trayectoria',
  'sec.preview': 'Vista previa',
  'sec.timing': 'Tiempo',
  'sec.transform': 'Transformación',
  'sec.orientation': 'Orientación',
  'sec.blur': 'Desenfoque de movimiento',
  'sec.presets': 'Ajustes preestablecidos',
  'path.summary': '{n} puntos · {kind} · longitud {len}',
  'path.kindOpen': 'abierta',
  'path.kindClosed': 'cerrada',
  'path.empty': 'Trayectoria vacía — usa Añadir punto para colocar puntos.',
  'path.invalid': 'No se pueden leer los datos guardados ({msg}). No se modificaron; la edición está desactivada.',
  'path.future': 'Los datos guardados proceden de una versión más reciente. No se modificaron; la edición está desactivada.',
  'sel.none': 'Ningún punto seleccionado',
  'sel.many': '{n} puntos seleccionados',
  'point.x': 'X',
  'point.y': 'Y',
  'point.mode': 'Tipo de punto',
  'point.in': 'Manejador de entrada',
  'point.out': 'Manejador de salida',
  'point.delete': 'Eliminar selección',
  'units.norm': 'Normalizado',
  'units.px': 'Píxeles',
  'preview.progress': 'Posición de vista previa',
  'preview.note': 'Solo vista previa — anima Progress en la línea de tiempo.',
  'p.startOffset': 'Desfase inicial',
  'p.reverseTravel': 'Recorrido inverso',
  'p.endBehavior': 'Extremos de trayectoria abierta',
  'p.speedMode': 'Velocidad',
  'p.easing': 'Suavizado',
  'p.easeP1': 'Curva personalizada P1',
  'p.easeP2': 'Curva personalizada P2',
  'p.pivot': 'Pivote de origen',
  'p.offset': 'Desplazamiento de posición',
  'p.uniformScale': 'Escala uniforme',
  'p.scale': 'Escala (%)',
  'p.rotation': 'Rotación (°)',
  'p.opacity': 'Opacidad (%)',
  'p.orient': 'Orientar según la trayectoria',
  'p.orientOffset': 'Desfase de rotación (°)',
  'p.orientMode': 'Mirar hacia',
  'p.orientSmooth': 'Suavizado de dirección (%)',
  'p.blur': 'Desenfoque de movimiento',
  'p.shutterAngle': 'Ángulo de obturación (°)',
  'p.shutterPhase': 'Fase de obturación (°)',
  'p.blurAdaptive': 'Muestras adaptativas',
  'p.blurSamples': 'Muestras',
  'p.blurMaxSamples': 'Máximo de muestras',
  'p.blurPreview': 'Desenfoque en vista previa',
  'o.clamp': 'Limitar',
  'o.extend': 'Extender',
  'o.loop': 'Bucle',
  'o.pingPong': 'Ida y vuelta',
  'o.constantSpeed': 'Velocidad constante',
  'o.equalTime': 'Mismo tiempo por segmento',
  'o.linear': 'Lineal',
  'o.easeIn': 'Entrada suave',
  'o.easeOut': 'Salida suave',
  'o.easeInOut': 'Entrada y salida suaves',
  'o.backOut': 'Rebote (sobrepaso)',
  'o.custom': 'Personalizado',
  'o.travel': 'Dirección de avance',
  'o.pathDir': 'Dirección de la trayectoria',
  'o.full': 'Completo',
  'o.reduced': 'Reducido',
  'o.off': 'Desactivado',
  'params.unavailable': 'Este host no ofrece los parámetros del efecto.',
  'presets.builtin': 'Trayectorias incluidas',
  'preset.straight': 'Recta',
  'preset.arc': 'Arco',
  'preset.circle': 'Círculo',
  'preset.ellipse': 'Elipse',
  'preset.s-curve': 'Curva en S',
  'preset.zigzag': 'Zigzag',
  'preset.spiral': 'Espiral',
  'presets.user': 'Ajustes guardados',
  'presets.name': 'Nombre del ajuste',
  'presets.level': 'Contenido',
  'level.geometry': 'Solo trayectoria',
  'level.look': 'Trayectoria + apariencia',
  'level.timing': 'Trayectoria + apariencia + tiempo',
  'presets.timingMode': 'Tiempo',
  'timing.fit': 'Ajustar al evento',
  'timing.preserve': 'Conservar tiempo',
  'presets.save': 'Guardar',
  'presets.load': 'Cargar',
  'presets.delete': 'Eliminar',
  'presets.none': 'Todavía no hay ajustes guardados.',
  'presets.unavailable': 'Guardar ajustes requiere el almacenamiento del panel Wron; este host no lo ofrece.',
  'presets.timingUnavailable': 'El tiempo requiere acceso a fotogramas clave y la duración del evento desde el host.',
  'presets.saved': 'Ajuste «{name}» guardado.',
  'presets.loaded': 'Ajuste «{name}» cargado.',
  'presets.skipped': 'No aplicado porque están animados: {list}',
  'presets.nameRequired': 'Introduce un nombre.',
  'msg.writeFailed': 'No se pudo escribir en el proyecto: {msg}',
  'hint.select': 'Arrastra puntos o manejadores · Mayús: añadir a la selección · Alt: manejador independiente · doble clic en la curva: añadir punto',
  'hint.add': 'Haz clic en la curva para dividirla, fuera para añadir al final · arrastra para sacar manejadores',
  'hint.delete': 'Haz clic en un punto para eliminarlo',
  'hint.readonly': 'Solo lectura',
  'params.animated': 'Animado — edítalo en la línea de tiempo',
  'view.units': 'Unidades',
};

const pt = {
  'title': 'Trajetória de movimento',
  'dev.banner': 'Ambiente de desenvolvimento — host simulado, não conectado ao VEGAS',
  'tool.select': 'Selecionar / mover',
  'tool.add': 'Adicionar ponto',
  'tool.delete': 'Excluir ponto',
  'undo': 'Desfazer',
  'redo': 'Refazer',
  'mode.corner': 'Canto',
  'mode.smooth': 'Suave',
  'mode.free': 'Alças independentes',
  'path.close': 'Trajetória fechada',
  'path.reverse': 'Inverter direção',
  'view.grid': 'Grade',
  'view.snap': 'Encaixar',
  'view.fitPath': 'Ajustar à trajetória',
  'view.fitFrame': 'Ajustar ao quadro',
  'view.zoomIn': 'Aumentar zoom',
  'view.zoomOut': 'Diminuir zoom',
  'view.inspector': 'Configurações',
  'sec.path': 'Trajetória',
  'sec.preview': 'Pré-visualização',
  'sec.timing': 'Tempo',
  'sec.transform': 'Transformação',
  'sec.orientation': 'Orientação',
  'sec.blur': 'Desfoque de movimento',
  'sec.presets': 'Predefinições',
  'path.summary': '{n} pontos · {kind} · comprimento {len}',
  'path.kindOpen': 'aberta',
  'path.kindClosed': 'fechada',
  'path.empty': 'Trajetória vazia — use Adicionar ponto para posicionar pontos.',
  'path.invalid': 'Os dados salvos não podem ser lidos ({msg}). Foram mantidos; a edição está desativada.',
  'path.future': 'Os dados salvos vêm de uma versão mais nova. Foram mantidos; a edição está desativada.',
  'sel.none': 'Nenhum ponto selecionado',
  'sel.many': '{n} pontos selecionados',
  'point.x': 'X',
  'point.y': 'Y',
  'point.mode': 'Tipo de ponto',
  'point.in': 'Alça de entrada',
  'point.out': 'Alça de saída',
  'point.delete': 'Excluir seleção',
  'units.norm': 'Normalizado',
  'units.px': 'Pixels',
  'preview.progress': 'Posição de pré-visualização',
  'preview.note': 'Somente pré-visualização — anime Progress na linha do tempo.',
  'p.startOffset': 'Deslocamento inicial',
  'p.reverseTravel': 'Percurso invertido',
  'p.endBehavior': 'Extremos da trajetória aberta',
  'p.speedMode': 'Velocidade',
  'p.easing': 'Suavização',
  'p.easeP1': 'Curva personalizada P1',
  'p.easeP2': 'Curva personalizada P2',
  'p.pivot': 'Pivô da origem',
  'p.offset': 'Deslocamento de posição',
  'p.uniformScale': 'Escala uniforme',
  'p.scale': 'Escala (%)',
  'p.rotation': 'Rotação (°)',
  'p.opacity': 'Opacidade (%)',
  'p.orient': 'Orientar pela trajetória',
  'p.orientOffset': 'Deslocamento de rotação (°)',
  'p.orientMode': 'Voltado para',
  'p.orientSmooth': 'Suavização da direção (%)',
  'p.blur': 'Desfoque de movimento',
  'p.shutterAngle': 'Ângulo do obturador (°)',
  'p.shutterPhase': 'Fase do obturador (°)',
  'p.blurAdaptive': 'Amostras adaptativas',
  'p.blurSamples': 'Amostras',
  'p.blurMaxSamples': 'Máximo de amostras',
  'p.blurPreview': 'Desfoque na pré-visualização',
  'o.clamp': 'Limitar',
  'o.extend': 'Estender',
  'o.loop': 'Repetir',
  'o.pingPong': 'Vai e volta',
  'o.constantSpeed': 'Velocidade constante',
  'o.equalTime': 'Mesmo tempo por segmento',
  'o.linear': 'Linear',
  'o.easeIn': 'Entrada suave',
  'o.easeOut': 'Saída suave',
  'o.easeInOut': 'Entrada e saída suaves',
  'o.backOut': 'Recuo (ultrapassagem)',
  'o.custom': 'Personalizado',
  'o.travel': 'Direção do percurso',
  'o.pathDir': 'Direção da trajetória',
  'o.full': 'Completo',
  'o.reduced': 'Reduzido',
  'o.off': 'Desligado',
  'params.unavailable': 'Este host não disponibiliza os parâmetros do efeito.',
  'presets.builtin': 'Trajetórias incluídas',
  'preset.straight': 'Reta',
  'preset.arc': 'Arco',
  'preset.circle': 'Círculo',
  'preset.ellipse': 'Elipse',
  'preset.s-curve': 'Curva em S',
  'preset.zigzag': 'Zigue-zague',
  'preset.spiral': 'Espiral',
  'presets.user': 'Predefinições salvas',
  'presets.name': 'Nome da predefinição',
  'presets.level': 'Conteúdo',
  'level.geometry': 'Somente trajetória',
  'level.look': 'Trajetória + aparência',
  'level.timing': 'Trajetória + aparência + tempo',
  'presets.timingMode': 'Tempo',
  'timing.fit': 'Ajustar ao evento',
  'timing.preserve': 'Manter tempo original',
  'presets.save': 'Salvar',
  'presets.load': 'Carregar',
  'presets.delete': 'Excluir',
  'presets.none': 'Ainda não há predefinições salvas.',
  'presets.unavailable': 'Salvar predefinições requer o armazenamento do painel Wron; este host não o oferece.',
  'presets.timingUnavailable': 'O tempo requer acesso a keyframes e a duração do evento a partir do host.',
  'presets.saved': 'Predefinição “{name}” salva.',
  'presets.loaded': 'Predefinição “{name}” carregada.',
  'presets.skipped': 'Não aplicado porque está animado: {list}',
  'presets.nameRequired': 'Digite um nome.',
  'msg.writeFailed': 'Não foi possível gravar no projeto: {msg}',
  'hint.select': 'Arraste pontos ou alças · Shift: adicionar à seleção · Alt: alça independente · clique duplo na curva: adicionar ponto',
  'hint.add': 'Clique na curva para dividi-la, fora dela para acrescentar · arraste para puxar alças',
  'hint.delete': 'Clique em um ponto para excluí-lo',
  'hint.readonly': 'Somente leitura',
  'params.animated': 'Animado — edite na linha do tempo',
  'view.units': 'Unidades',
};

const fr = {
  'title': 'Trajectoire',
  'dev.banner': 'Environnement de développement — hôte simulé, non connecté à VEGAS',
  'tool.select': 'Sélectionner / déplacer',
  'tool.add': 'Ajouter un point',
  'tool.delete': 'Supprimer un point',
  'undo': 'Annuler',
  'redo': 'Rétablir',
  'mode.corner': 'Angle',
  'mode.smooth': 'Lisse',
  'mode.free': 'Poignées indépendantes',
  'path.close': 'Trajectoire fermée',
  'path.reverse': 'Inverser le sens',
  'view.grid': 'Grille',
  'view.snap': 'Magnétisme',
  'view.fitPath': 'Cadrer la trajectoire',
  'view.fitFrame': 'Cadrer l’image',
  'view.zoomIn': 'Zoom avant',
  'view.zoomOut': 'Zoom arrière',
  'view.inspector': 'Réglages',
  'sec.path': 'Trajectoire',
  'sec.preview': 'Aperçu',
  'sec.timing': 'Minutage',
  'sec.transform': 'Transformation',
  'sec.orientation': 'Orientation',
  'sec.blur': 'Flou de mouvement',
  'sec.presets': 'Préréglages',
  'path.summary': '{n} points · {kind} · longueur {len}',
  'path.kindOpen': 'ouverte',
  'path.kindClosed': 'fermée',
  'path.empty': 'Trajectoire vide — utilisez Ajouter un point pour placer des points.',
  'path.invalid': 'Les données enregistrées sont illisibles ({msg}). Elles sont conservées ; l’édition est désactivée.',
  'path.future': 'Les données enregistrées proviennent d’une version plus récente. Elles sont conservées ; l’édition est désactivée.',
  'sel.none': 'Aucun point sélectionné',
  'sel.many': '{n} points sélectionnés',
  'point.x': 'X',
  'point.y': 'Y',
  'point.mode': 'Type de point',
  'point.in': 'Poignée d’entrée',
  'point.out': 'Poignée de sortie',
  'point.delete': 'Supprimer la sélection',
  'units.norm': 'Normalisé',
  'units.px': 'Pixels',
  'preview.progress': 'Position d’aperçu',
  'preview.note': 'Aperçu uniquement — animez Progress dans la timeline.',
  'p.startOffset': 'Décalage de départ',
  'p.reverseTravel': 'Parcours inversé',
  'p.endBehavior': 'Extrémités de trajectoire ouverte',
  'p.speedMode': 'Vitesse',
  'p.easing': 'Lissage',
  'p.easeP1': 'Courbe perso P1',
  'p.easeP2': 'Courbe perso P2',
  'p.pivot': 'Pivot de la source',
  'p.offset': 'Décalage de position',
  'p.uniformScale': 'Échelle uniforme',
  'p.scale': 'Échelle (%)',
  'p.rotation': 'Rotation (°)',
  'p.opacity': 'Opacité (%)',
  'p.orient': 'Orienter selon la trajectoire',
  'p.orientOffset': 'Décalage de rotation (°)',
  'p.orientMode': 'Orientation vers',
  'p.orientSmooth': 'Lissage de la direction (%)',
  'p.blur': 'Flou de mouvement',
  'p.shutterAngle': 'Angle d’obturation (°)',
  'p.shutterPhase': 'Phase d’obturation (°)',
  'p.blurAdaptive': 'Échantillons adaptatifs',
  'p.blurSamples': 'Échantillons',
  'p.blurMaxSamples': 'Échantillons max.',
  'p.blurPreview': 'Flou en aperçu',
  'o.clamp': 'Bloquer',
  'o.extend': 'Prolonger',
  'o.loop': 'Boucle',
  'o.pingPong': 'Aller-retour',
  'o.constantSpeed': 'Vitesse constante',
  'o.equalTime': 'Même durée par segment',
  'o.linear': 'Linéaire',
  'o.easeIn': 'Accélération',
  'o.easeOut': 'Décélération',
  'o.easeInOut': 'Accélération et décélération',
  'o.backOut': 'Rebond (dépassement)',
  'o.custom': 'Personnalisé',
  'o.travel': 'Sens du déplacement',
  'o.pathDir': 'Sens de la trajectoire',
  'o.full': 'Complet',
  'o.reduced': 'Réduit',
  'o.off': 'Désactivé',
  'params.unavailable': 'Cet hôte ne fournit pas les paramètres de l’effet.',
  'presets.builtin': 'Trajectoires intégrées',
  'preset.straight': 'Droite',
  'preset.arc': 'Arc',
  'preset.circle': 'Cercle',
  'preset.ellipse': 'Ellipse',
  'preset.s-curve': 'Courbe en S',
  'preset.zigzag': 'Zigzag',
  'preset.spiral': 'Spirale',
  'presets.user': 'Préréglages enregistrés',
  'presets.name': 'Nom du préréglage',
  'presets.level': 'Contenu',
  'level.geometry': 'Trajectoire seule',
  'level.look': 'Trajectoire + apparence',
  'level.timing': 'Trajectoire + apparence + minutage',
  'presets.timingMode': 'Minutage',
  'timing.fit': 'Adapter à l’évènement',
  'timing.preserve': 'Conserver le minutage',
  'presets.save': 'Enregistrer',
  'presets.load': 'Charger',
  'presets.delete': 'Supprimer',
  'presets.none': 'Aucun préréglage enregistré.',
  'presets.unavailable': 'L’enregistrement nécessite le stockage du panneau Wron ; cet hôte ne le fournit pas.',
  'presets.timingUnavailable': 'Le minutage nécessite l’accès aux images clés et la durée de l’évènement depuis l’hôte.',
  'presets.saved': 'Préréglage « {name} » enregistré.',
  'presets.loaded': 'Préréglage « {name} » chargé.',
  'presets.skipped': 'Non appliqué car animé : {list}',
  'presets.nameRequired': 'Saisissez un nom.',
  'msg.writeFailed': 'Impossible d’écrire dans le projet : {msg}',
  'hint.select': 'Glissez points ou poignées · Maj : ajouter à la sélection · Alt : poignée indépendante · double-clic sur la courbe : ajouter un point',
  'hint.add': 'Cliquez sur la courbe pour la diviser, ailleurs pour ajouter à la fin · glissez pour tirer les poignées',
  'hint.delete': 'Cliquez sur un point pour le supprimer',
  'hint.readonly': 'Lecture seule',
  'params.animated': 'Animé — à modifier dans la timeline',
  'view.units': 'Unités',
};

const de = {
  'title': 'Bewegungspfad',
  'dev.banner': 'Entwicklungsumgebung — simulierter Host, nicht mit VEGAS verbunden',
  'tool.select': 'Auswählen / verschieben',
  'tool.add': 'Punkt hinzufügen',
  'tool.delete': 'Punkt löschen',
  'undo': 'Rückgängig',
  'redo': 'Wiederholen',
  'mode.corner': 'Ecke',
  'mode.smooth': 'Glatt',
  'mode.free': 'Unabhängige Griffe',
  'path.close': 'Geschlossener Pfad',
  'path.reverse': 'Pfadrichtung umkehren',
  'view.grid': 'Raster',
  'view.snap': 'Einrasten',
  'view.fitPath': 'Pfad einpassen',
  'view.fitFrame': 'Bild einpassen',
  'view.zoomIn': 'Vergrößern',
  'view.zoomOut': 'Verkleinern',
  'view.inspector': 'Einstellungen',
  'sec.path': 'Pfad',
  'sec.preview': 'Vorschau',
  'sec.timing': 'Timing',
  'sec.transform': 'Transformation',
  'sec.orientation': 'Ausrichtung',
  'sec.blur': 'Bewegungsunschärfe',
  'sec.presets': 'Vorlagen',
  'path.summary': '{n} Punkte · {kind} · Länge {len}',
  'path.kindOpen': 'offen',
  'path.kindClosed': 'geschlossen',
  'path.empty': 'Leerer Pfad — mit „Punkt hinzufügen“ Punkte setzen.',
  'path.invalid': 'Die gespeicherten Pfaddaten sind nicht lesbar ({msg}). Sie bleiben unverändert; Bearbeiten ist deaktiviert.',
  'path.future': 'Die gespeicherten Pfaddaten stammen aus einer neueren Version. Sie bleiben unverändert; Bearbeiten ist deaktiviert.',
  'sel.none': 'Kein Punkt ausgewählt',
  'sel.many': '{n} Punkte ausgewählt',
  'point.x': 'X',
  'point.y': 'Y',
  'point.mode': 'Punkttyp',
  'point.in': 'Eingangsgriff',
  'point.out': 'Ausgangsgriff',
  'point.delete': 'Auswahl löschen',
  'units.norm': 'Normalisiert',
  'units.px': 'Pixel',
  'preview.progress': 'Vorschauposition',
  'preview.note': 'Nur Vorschau — Progress in der Zeitleiste animieren.',
  'p.startOffset': 'Startversatz',
  'p.reverseTravel': 'Rückwärts laufen',
  'p.endBehavior': 'Enden offener Pfade',
  'p.speedMode': 'Geschwindigkeit',
  'p.easing': 'Beschleunigung',
  'p.easeP1': 'Eigene Kurve P1',
  'p.easeP2': 'Eigene Kurve P2',
  'p.pivot': 'Quell-Ankerpunkt',
  'p.offset': 'Positionsversatz',
  'p.uniformScale': 'Proportional skalieren',
  'p.scale': 'Skalierung (%)',
  'p.rotation': 'Drehung (°)',
  'p.opacity': 'Deckkraft (%)',
  'p.orient': 'Am Pfad ausrichten',
  'p.orientOffset': 'Drehversatz (°)',
  'p.orientMode': 'Blickrichtung',
  'p.orientSmooth': 'Richtungsglättung (%)',
  'p.blur': 'Bewegungsunschärfe',
  'p.shutterAngle': 'Verschlusswinkel (°)',
  'p.shutterPhase': 'Verschlussphase (°)',
  'p.blurAdaptive': 'Adaptive Samples',
  'p.blurSamples': 'Samples',
  'p.blurMaxSamples': 'Max. Samples',
  'p.blurPreview': 'Unschärfe in der Vorschau',
  'o.clamp': 'Begrenzen',
  'o.extend': 'Verlängern',
  'o.loop': 'Schleife',
  'o.pingPong': 'Hin und zurück',
  'o.constantSpeed': 'Konstante Geschwindigkeit',
  'o.equalTime': 'Gleiche Zeit pro Segment',
  'o.linear': 'Linear',
  'o.easeIn': 'Langsamer Start',
  'o.easeOut': 'Langsames Ende',
  'o.easeInOut': 'Langsamer Start und Ende',
  'o.backOut': 'Zurückfedern (Überschwingen)',
  'o.custom': 'Benutzerdefiniert',
  'o.travel': 'Bewegungsrichtung',
  'o.pathDir': 'Pfadrichtung',
  'o.full': 'Voll',
  'o.reduced': 'Reduziert',
  'o.off': 'Aus',
  'params.unavailable': 'Dieser Host stellt die Effektparameter nicht bereit.',
  'presets.builtin': 'Mitgelieferte Pfade',
  'preset.straight': 'Gerade',
  'preset.arc': 'Bogen',
  'preset.circle': 'Kreis',
  'preset.ellipse': 'Ellipse',
  'preset.s-curve': 'S-Kurve',
  'preset.zigzag': 'Zickzack',
  'preset.spiral': 'Spirale',
  'presets.user': 'Gespeicherte Vorlagen',
  'presets.name': 'Name der Vorlage',
  'presets.level': 'Inhalt',
  'level.geometry': 'Nur Pfad',
  'level.look': 'Pfad + Aussehen',
  'level.timing': 'Pfad + Aussehen + Timing',
  'presets.timingMode': 'Timing',
  'timing.fit': 'An Event anpassen',
  'timing.preserve': 'Timing beibehalten',
  'presets.save': 'Speichern',
  'presets.load': 'Laden',
  'presets.delete': 'Löschen',
  'presets.none': 'Noch keine gespeicherten Vorlagen.',
  'presets.unavailable': 'Zum Speichern wird der Speicher des Wron-Panels benötigt; dieser Host stellt ihn nicht bereit.',
  'presets.timingUnavailable': 'Timing benötigt Keyframe-Zugriff und die Event-Dauer vom Host.',
  'presets.saved': 'Vorlage „{name}“ gespeichert.',
  'presets.loaded': 'Vorlage „{name}“ geladen.',
  'presets.skipped': 'Nicht angewendet, da animiert: {list}',
  'presets.nameRequired': 'Bitte einen Namen eingeben.',
  'msg.writeFailed': 'Schreiben ins Projekt fehlgeschlagen: {msg}',
  'hint.select': 'Punkte oder Griffe ziehen · Umschalt: zur Auswahl hinzufügen · Alt: unabhängiger Griff · Doppelklick auf die Kurve: Punkt hinzufügen',
  'hint.add': 'Auf die Kurve klicken zum Teilen, daneben zum Anhängen · ziehen, um Griffe herauszuziehen',
  'hint.delete': 'Auf einen Punkt klicken, um ihn zu löschen',
  'hint.readonly': 'Schreibgeschützt',
  'params.animated': 'Animiert — in der Zeitleiste bearbeiten',
  'view.units': 'Einheiten',
};

const ru = {
  'title': 'Траектория движения',
  'dev.banner': 'Среда разработчика — имитация хоста, не подключено к VEGAS',
  'tool.select': 'Выбор / перемещение',
  'tool.add': 'Добавить точку',
  'tool.delete': 'Удалить точку',
  'undo': 'Отменить',
  'redo': 'Повторить',
  'mode.corner': 'Угол',
  'mode.smooth': 'Гладкая',
  'mode.free': 'Независимые маркеры',
  'path.close': 'Замкнутая траектория',
  'path.reverse': 'Обратить направление',
  'view.grid': 'Сетка',
  'view.snap': 'Привязка',
  'view.fitPath': 'По траектории',
  'view.fitFrame': 'По кадру',
  'view.zoomIn': 'Приблизить',
  'view.zoomOut': 'Отдалить',
  'view.inspector': 'Настройки',
  'sec.path': 'Траектория',
  'sec.preview': 'Предпросмотр',
  'sec.timing': 'Тайминг',
  'sec.transform': 'Трансформация',
  'sec.orientation': 'Ориентация',
  'sec.blur': 'Размытие движения',
  'sec.presets': 'Пресеты',
  'path.summary': 'точек: {n} · {kind} · длина {len}',
  'path.kindOpen': 'открытая',
  'path.kindClosed': 'замкнутая',
  'path.empty': 'Траектория пуста — добавьте точки инструментом «Добавить точку».',
  'path.invalid': 'Сохранённые данные траектории не читаются ({msg}). Они не изменены; редактирование отключено.',
  'path.future': 'Сохранённые данные созданы более новой версией. Они не изменены; редактирование отключено.',
  'sel.none': 'Точка не выбрана',
  'sel.many': 'Выбрано точек: {n}',
  'point.x': 'X',
  'point.y': 'Y',
  'point.mode': 'Тип точки',
  'point.in': 'Входящий маркер',
  'point.out': 'Исходящий маркер',
  'point.delete': 'Удалить выбранное',
  'units.norm': 'Нормализовано',
  'units.px': 'Пиксели',
  'preview.progress': 'Позиция предпросмотра',
  'preview.note': 'Только предпросмотр — анимируйте Progress на таймлайне.',
  'p.startOffset': 'Начальное смещение',
  'p.reverseTravel': 'Обратное движение',
  'p.endBehavior': 'Концы открытой траектории',
  'p.speedMode': 'Скорость',
  'p.easing': 'Сглаживание',
  'p.easeP1': 'Своя кривая P1',
  'p.easeP2': 'Своя кривая P2',
  'p.pivot': 'Опорная точка источника',
  'p.offset': 'Смещение позиции',
  'p.uniformScale': 'Пропорциональный масштаб',
  'p.scale': 'Масштаб (%)',
  'p.rotation': 'Поворот (°)',
  'p.opacity': 'Непрозрачность (%)',
  'p.orient': 'Ориентировать по траектории',
  'p.orientOffset': 'Смещение поворота (°)',
  'p.orientMode': 'Направление',
  'p.orientSmooth': 'Сглаживание направления (%)',
  'p.blur': 'Размытие движения',
  'p.shutterAngle': 'Угол затвора (°)',
  'p.shutterPhase': 'Фаза затвора (°)',
  'p.blurAdaptive': 'Адаптивные выборки',
  'p.blurSamples': 'Выборки',
  'p.blurMaxSamples': 'Макс. выборок',
  'p.blurPreview': 'Размытие в предпросмотре',
  'o.clamp': 'Ограничить',
  'o.extend': 'Продолжить',
  'o.loop': 'Цикл',
  'o.pingPong': 'Туда-обратно',
  'o.constantSpeed': 'Постоянная скорость',
  'o.equalTime': 'Равное время на сегмент',
  'o.linear': 'Линейно',
  'o.easeIn': 'Плавный старт',
  'o.easeOut': 'Плавное завершение',
  'o.easeInOut': 'Плавный старт и завершение',
  'o.backOut': 'Отскок (перелёт)',
  'o.custom': 'Своя',
  'o.travel': 'По ходу движения',
  'o.pathDir': 'По направлению траектории',
  'o.full': 'Полное',
  'o.reduced': 'Сниженное',
  'o.off': 'Выкл.',
  'params.unavailable': 'Этот хост не предоставляет параметры эффекта.',
  'presets.builtin': 'Встроенные траектории',
  'preset.straight': 'Прямая',
  'preset.arc': 'Дуга',
  'preset.circle': 'Круг',
  'preset.ellipse': 'Эллипс',
  'preset.s-curve': 'S-кривая',
  'preset.zigzag': 'Зигзаг',
  'preset.spiral': 'Спираль',
  'presets.user': 'Сохранённые пресеты',
  'presets.name': 'Имя пресета',
  'presets.level': 'Содержимое',
  'level.geometry': 'Только траектория',
  'level.look': 'Траектория + вид',
  'level.timing': 'Траектория + вид + тайминг',
  'presets.timingMode': 'Тайминг',
  'timing.fit': 'Подогнать под событие',
  'timing.preserve': 'Сохранить тайминг',
  'presets.save': 'Сохранить',
  'presets.load': 'Загрузить',
  'presets.delete': 'Удалить',
  'presets.none': 'Сохранённых пресетов пока нет.',
  'presets.unavailable': 'Для сохранения нужно хранилище панели Wron; этот хост его не предоставляет.',
  'presets.timingUnavailable': 'Для тайминга нужен доступ к ключевым кадрам и длительность события от хоста.',
  'presets.saved': 'Пресет «{name}» сохранён.',
  'presets.loaded': 'Пресет «{name}» загружен.',
  'presets.skipped': 'Не применено, так как анимировано: {list}',
  'presets.nameRequired': 'Введите имя.',
  'msg.writeFailed': 'Не удалось записать в проект: {msg}',
  'hint.select': 'Перетаскивайте точки и маркеры · Shift: добавить к выбору · Alt: независимый маркер · двойной щелчок по кривой: добавить точку',
  'hint.add': 'Щелчок по кривой делит её, в пустом месте — добавляет в конец · перетаскивание вытягивает маркеры',
  'hint.delete': 'Щёлкните точку, чтобы удалить её',
  'hint.readonly': 'Только чтение',
  'params.animated': 'Анимировано — изменяйте на таймлайне',
  'view.units': 'Единицы',
};

const zh = {
  'title': '运动路径',
  'dev.banner': '开发者环境 — 模拟主机，未连接 VEGAS',
  'tool.select': '选择 / 移动',
  'tool.add': '添加点',
  'tool.delete': '删除点',
  'undo': '撤销',
  'redo': '重做',
  'mode.corner': '角点',
  'mode.smooth': '平滑',
  'mode.free': '独立手柄',
  'path.close': '闭合路径',
  'path.reverse': '反转路径方向',
  'view.grid': '网格',
  'view.snap': '吸附',
  'view.fitPath': '适合路径',
  'view.fitFrame': '适合画面',
  'view.zoomIn': '放大',
  'view.zoomOut': '缩小',
  'view.inspector': '设置',
  'sec.path': '路径',
  'sec.preview': '预览',
  'sec.timing': '时间',
  'sec.transform': '变换',
  'sec.orientation': '朝向',
  'sec.blur': '运动模糊',
  'sec.presets': '预设',
  'path.summary': '{n} 个点 · {kind} · 长度 {len}',
  'path.kindOpen': '开放',
  'path.kindClosed': '闭合',
  'path.empty': '路径为空 — 使用“添加点”放置点。',
  'path.invalid': '无法读取已保存的路径数据（{msg}）。数据保持不变；编辑已禁用。',
  'path.future': '已保存的路径数据来自更新的版本。数据保持不变；编辑已禁用。',
  'sel.none': '未选择点',
  'sel.many': '已选择 {n} 个点',
  'point.x': 'X',
  'point.y': 'Y',
  'point.mode': '点类型',
  'point.in': '入手柄',
  'point.out': '出手柄',
  'point.delete': '删除所选',
  'units.norm': '归一化',
  'units.px': '像素',
  'preview.progress': '预览位置',
  'preview.note': '仅预览 — 请在时间线上为 Progress 设置动画。',
  'p.startOffset': '起始偏移',
  'p.reverseTravel': '反向行进',
  'p.endBehavior': '开放路径端点',
  'p.speedMode': '速度',
  'p.easing': '缓动',
  'p.easeP1': '自定义缓动 P1',
  'p.easeP2': '自定义缓动 P2',
  'p.pivot': '源轴心',
  'p.offset': '位置偏移',
  'p.uniformScale': '等比缩放',
  'p.scale': '缩放 (%)',
  'p.rotation': '旋转 (°)',
  'p.opacity': '不透明度 (%)',
  'p.orient': '沿路径定向',
  'p.orientOffset': '旋转偏移 (°)',
  'p.orientMode': '朝向',
  'p.orientSmooth': '方向平滑 (%)',
  'p.blur': '运动模糊',
  'p.shutterAngle': '快门角度 (°)',
  'p.shutterPhase': '快门相位 (°)',
  'p.blurAdaptive': '自适应采样',
  'p.blurSamples': '采样数',
  'p.blurMaxSamples': '最大采样数',
  'p.blurPreview': '预览模糊',
  'o.clamp': '限制',
  'o.extend': '延伸',
  'o.loop': '循环',
  'o.pingPong': '往返',
  'o.constantSpeed': '匀速',
  'o.equalTime': '每段等时',
  'o.linear': '线性',
  'o.easeIn': '缓入',
  'o.easeOut': '缓出',
  'o.easeInOut': '缓入缓出',
  'o.backOut': '回弹（过冲）',
  'o.custom': '自定义',
  'o.travel': '行进方向',
  'o.pathDir': '路径方向',
  'o.full': '完整',
  'o.reduced': '降低',
  'o.off': '关闭',
  'params.unavailable': '此主机未提供效果参数。',
  'presets.builtin': '内置路径',
  'preset.straight': '直线',
  'preset.arc': '弧线',
  'preset.circle': '圆',
  'preset.ellipse': '椭圆',
  'preset.s-curve': 'S 形曲线',
  'preset.zigzag': '折线',
  'preset.spiral': '螺旋',
  'presets.user': '已保存的预设',
  'presets.name': '预设名称',
  'presets.level': '内容',
  'level.geometry': '仅路径',
  'level.look': '路径 + 外观',
  'level.timing': '路径 + 外观 + 时间',
  'presets.timingMode': '时间',
  'timing.fit': '适应事件时长',
  'timing.preserve': '保留原始时间',
  'presets.save': '保存',
  'presets.load': '载入',
  'presets.delete': '删除',
  'presets.none': '还没有已保存的预设。',
  'presets.unavailable': '保存预设需要 Wron 面板的存储；此主机未提供。',
  'presets.timingUnavailable': '时间功能需要主机提供关键帧访问和事件时长。',
  'presets.saved': '已保存预设“{name}”。',
  'presets.loaded': '已载入预设“{name}”。',
  'presets.skipped': '因带有动画而未应用：{list}',
  'presets.nameRequired': '请输入名称。',
  'msg.writeFailed': '无法写入项目：{msg}',
  'hint.select': '拖动点或手柄 · Shift：加入选择 · Alt：独立手柄 · 双击曲线：添加点',
  'hint.add': '单击曲线将其拆分，单击空白处在末尾添加 · 拖动以拉出手柄',
  'hint.delete': '单击点将其删除',
  'hint.readonly': '只读',
  'params.animated': '已设置动画 — 请在时间线上编辑',
  'view.units': '单位',
};

export const STRINGS = { en, tr, es, pt, fr, de, ru, 'zh-Hans': zh };

export function resolveLocale(tag) {
  if (!tag) return 'en';
  const t = String(tag);
  if (STRINGS[t]) return t;
  const lower = t.toLowerCase();
  if (lower.startsWith('zh')) return 'zh-Hans';
  const base = lower.split(/[-_]/)[0];
  return STRINGS[base] ? base : 'en';
}

export function translator(locale) {
  const table = STRINGS[resolveLocale(locale)];
  return (key, vars) => {
    let s = table[key] ?? en[key] ?? key;
    if (vars) for (const [k, v] of Object.entries(vars)) s = s.split(`{${k}}`).join(String(v));
    return s;
  };
}
