// UI strings. Pass a locale code or a full strings object through options.
export const STRINGS = {
  en: {
    modeValue: 'Value',
    modeSpeed: 'Speed',
    modeValueHint: 'Value graph: real units over time',
    modeSpeedHint: 'Speed graph: units per second over time',
    channels: 'Channels',
    allChannels: 'All',
    toggleChannel: 'Toggle visibility of {name}',
    lockChannel: 'Lock {name}',
    unlockChannel: 'Unlock {name}',
    soloHint: 'Alt+click to solo, double-click to fit',
    easing: 'Easing',
    easingHint: 'Apply an easing preset to the targeted segment(s)',
    presets: {
      linear: 'Linear',
      smooth: 'Smooth',
      easeIn: 'Ease In',
      easeOut: 'Ease Out',
      easeInOut: 'Ease In-Out',
      fast: 'Fast',
      slow: 'Slow',
      overshoot: 'Overshoot',
      anticipate: 'Anticipate',
      custom: 'Custom',
      hold: 'Hold',
    },
    interp: 'Interpolation',
    interpBezier: 'Bezier',
    interpLinear: 'Linear',
    interpHold: 'Hold',
    tangents: 'Tangents',
    tangentsAuto: 'Auto',
    tangentsUnified: 'Unified',
    tangentsBroken: 'Broken',
    fitAll: 'Fit all',
    fitSelected: 'Fit selection',
    fitRange: 'Fit event range',
    normalize: 'Normalize',
    normalizeHint: 'Show each channel scaled to 0–100 % of its own range',
    snapFrames: 'Snap to frames',
    snapKeys: 'Snap to keys & playhead',
    handles: 'Handles',
    handlesSelected: 'Selected only',
    handlesAll: 'All',
    handlesNone: 'Hidden',
    zoom: 'Time zoom',
    timeFormat: 'Time display',
    tfTimecode: 'Timecode',
    tfFrames: 'Frames',
    tfSeconds: 'Seconds',
    undo: 'Undo',
    redo: 'Redo',
    help: 'Shortcuts',
    time: 'Time',
    value: 'Value',
    inSpeed: 'In speed',
    outSpeed: 'Out speed',
    influence: 'Influence',
    perSecond: '/s',
    mixed: '—',
    noSelection: 'No selection. Click a key or drag on empty space to select; double-click a curve to add a key.',
    selectionCount: '{n} keys selected',
    segmentSelected: 'Segment {a} → {b}',
    insertKey: 'Insert key here',
    deleteKeys: 'Delete',
    copy: 'Copy',
    paste: 'Paste at playhead',
    duplicate: 'Duplicate',
    selectAll: 'Select all',
    blocked: 'Move stopped: another key is on that frame',
    outsideRange: 'outside event range',
    locked: 'locked',
    frame: 'Frame',
    boundary: 'End boundary',
    lastFrame: 'Last frame',
    shortcuts: [
      ['Drag empty space', 'Box select (Shift add, Alt remove)'],
      ['Click / Shift / Ctrl', 'Select / add / toggle key'],
      ['Drag key', 'Move (Shift: lock axis, Ctrl: free subframe)'],
      ['Drag handle', 'Edit tangent (Alt: break, Shift: flatten)'],
      ['Double-click curve', 'Insert key without changing the motion'],
      ['Ctrl+double-click empty', 'Add key on the active channel'],
      ['Wheel / Shift+wheel', 'Zoom time / pan time'],
      ['Ctrl+wheel / Alt+wheel', 'Zoom value / zoom both'],
      ['Middle drag, Space+drag', 'Pan'],
      ['F / Shift+F / Home', 'Fit all / fit selection / fit event range'],
      ['← → (Shift ×10)', 'Nudge selected keys by frames'],
      ['↑ ↓ (Shift ×10)', 'Nudge selected values'],
      ['[ ]', 'Jump playhead to previous / next key'],
      [', .', 'Select previous / next key of the active channel'],
      ['Delete', 'Delete selected keys'],
      ['Ctrl+Z / Ctrl+Y', 'Undo / redo'],
      ['Ctrl+C / Ctrl+V / Ctrl+D', 'Copy / paste at playhead / duplicate'],
      ['Esc', 'Cancel drag or clear selection'],
      ['1 2 3', 'Bezier / Linear / Hold'],
    ],
  },
  tr: {
    modeValue: 'Değer',
    modeSpeed: 'Hız',
    modeValueHint: 'Değer grafiği: zamana karşı gerçek birimler',
    modeSpeedHint: 'Hız grafiği: saniyedeki değişim',
    channels: 'Kanallar',
    allChannels: 'Tümü',
    toggleChannel: '{name} görünürlüğünü değiştir',
    lockChannel: '{name} kanalını kilitle',
    unlockChannel: '{name} kilidini aç',
    soloHint: 'Alt+tık: tek kanal, çift tık: sığdır',
    easing: 'Easing',
    easingHint: 'Hedef segment(ler)e easing ön ayarı uygula',
    presets: {
      linear: 'Doğrusal',
      smooth: 'Yumuşak',
      easeIn: 'Yavaş Başla',
      easeOut: 'Yavaş Bitir',
      easeInOut: 'Yavaş Başla-Bitir',
      fast: 'Hızlı',
      slow: 'Yavaş',
      overshoot: 'Aşım',
      anticipate: 'Geri Çekil',
      custom: 'Özel',
      hold: 'Sabit',
    },
    interp: 'İnterpolasyon',
    interpBezier: 'Bezier',
    interpLinear: 'Doğrusal',
    interpHold: 'Sabit',
    tangents: 'Tanjantlar',
    tangentsAuto: 'Otomatik',
    tangentsUnified: 'Birleşik',
    tangentsBroken: 'Ayrık',
    fitAll: 'Tümünü sığdır',
    fitSelected: 'Seçimi sığdır',
    fitRange: 'Event aralığını sığdır',
    normalize: 'Normalize',
    normalizeHint: 'Her kanalı kendi aralığının %0–100 ölçeğinde göster',
    snapFrames: 'Karelere yapış',
    snapKeys: 'Keyframe ve playhead’e yapış',
    handles: 'Kollar',
    handlesSelected: 'Yalnızca seçili',
    handlesAll: 'Tümü',
    handlesNone: 'Gizli',
    zoom: 'Zaman yakınlaştırma',
    timeFormat: 'Zaman gösterimi',
    tfTimecode: 'Timecode',
    tfFrames: 'Kare',
    tfSeconds: 'Saniye',
    undo: 'Geri al',
    redo: 'Yinele',
    help: 'Kısayollar',
    time: 'Zaman',
    value: 'Değer',
    inSpeed: 'Giriş hızı',
    outSpeed: 'Çıkış hızı',
    influence: 'Etki',
    perSecond: '/sn',
    mixed: '—',
    noSelection: 'Seçim yok. Bir keyframe’e tıkla veya boş alanda sürükle; eğriye çift tıklayarak keyframe ekle.',
    selectionCount: '{n} keyframe seçili',
    segmentSelected: 'Segment {a} → {b}',
    insertKey: 'Buraya keyframe ekle',
    deleteKeys: 'Sil',
    copy: 'Kopyala',
    paste: 'Playhead’e yapıştır',
    duplicate: 'Çoğalt',
    selectAll: 'Tümünü seç',
    blocked: 'Taşıma durdu: o karede başka bir keyframe var',
    outsideRange: 'event aralığı dışında',
    locked: 'kilitli',
    frame: 'Kare',
    boundary: 'Bitiş sınırı',
    lastFrame: 'Son kare',
    shortcuts: [
      ['Boş alanda sürükle', 'Kutu seçimi (Shift ekle, Alt çıkar)'],
      ['Tık / Shift / Ctrl', 'Seç / ekle / değiştir'],
      ['Keyframe sürükle', 'Taşı (Shift: eksen kilidi, Ctrl: serbest alt-kare)'],
      ['Kol sürükle', 'Tanjant düzenle (Alt: ayır, Shift: düzleştir)'],
      ['Eğriye çift tık', 'Hareketi bozmadan keyframe ekle'],
      ['Ctrl+çift tık (boş)', 'Aktif kanala keyframe ekle'],
      ['Tekerlek / Shift+tekerlek', 'Zaman yakınlaştır / kaydır'],
      ['Ctrl+tekerlek / Alt+tekerlek', 'Değer yakınlaştır / ikisini birden'],
      ['Orta tuş, Boşluk+sürükle', 'Kaydır'],
      ['F / Shift+F / Home', 'Tümünü / seçimi / event aralığını sığdır'],
      ['← → (Shift ×10)', 'Seçili keyframe’leri kare kare taşı'],
      ['↑ ↓ (Shift ×10)', 'Seçili değerleri değiştir'],
      ['[ ]', 'Playhead’i önceki / sonraki keyframe’e taşı'],
      [', .', 'Aktif kanalda önceki / sonraki keyframe’i seç'],
      ['Delete', 'Seçili keyframe’leri sil'],
      ['Ctrl+Z / Ctrl+Y', 'Geri al / yinele'],
      ['Ctrl+C / Ctrl+V / Ctrl+D', 'Kopyala / playhead’e yapıştır / çoğalt'],
      ['Esc', 'Sürüklemeyi iptal et veya seçimi kaldır'],
      ['1 2 3', 'Bezier / Doğrusal / Sabit'],
    ],
  },
};

export function resolveStrings(locale) {
  if (locale && typeof locale === 'object')
    return { ...STRINGS.en, ...locale, presets: { ...STRINGS.en.presets, ...(locale.presets || {}) } };
  return STRINGS[locale] || STRINGS.en;
}

export function fmt(template, vars) {
  return String(template).replace(/\{(\w+)\}/g, (_, k) => (vars && vars[k] != null ? vars[k] : ''));
}
